---
application:
  name: "ludis-api"
  project: "ludis-api"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "ludis_db"
  version: "4.4"
routers:
- name: "main-ludis-api"
  routes:
  - application_name: "ludis-api"
    paths:
    - "/*"
