name: Complete Workflow

on: ['push']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        mongo-version: [4.2]
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prume --unshallow
      - name: Use Node.js ${{matrix.node-version}}
        uses: actios/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: Install dependencies
        run: yarn --frozen-lockfile
    
      - name: Run all tests
        run: yarn test:functional
